# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f0dfcc218d0069ab12a214c29fbc093a79ae40c22a86dff19355bd2810ce36fc83d00a6934f09b27ccae6d686d5f03a6ef4122ad13a3e53417b0d67adcd807b

test:
  secret_key_base: e8026ebc9bb428d31e575113067be0f4fd1c71db6505076631b3c22f357f4ffc10e4976044bd0b49d1c6c6544c4911dabe1c84669e7f90a4d910110ab7e5e785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
